### ISSUE TITLE
建议：丰富options配置参数

### ISSUE THREAD

**Issue by cooppor** [CoderMonkie/js-watermarker#8]
首先非常感谢您开发的如此好用库，在开发时能完美的实现业务需要。
但是在使用过程中发现有些地方需要再提升一下，让这个库更好的服务广大开发者。
以下是在我使用过程中觉得需要再提升的建议：
1. options中添加一个debug:boolean参数。如果此参数设置为true时，再输出相关console.log打印内容。因为，这些开发时，现有的几个console.log输出的东西和次数太多了，有点影响别的调试内容的观察了。这些输出出发点肯定是好的，也能帮助到需要的人，但是现在有点不太友好了，希望可以改进。
2. options中添加一个zIndex:number参数。当然当前的默认值是大多数场景下是够用的。但是有些时候想让部分有些内容上不输出水印。当然，可以调研内容自己的z-index值来解决这个问题，但是，这需要调整非常大的zIndex值，需要权衡其他层级。
以上是我在使用过程中的感觉，希望能采纳，非常感谢。

**Comment by CoderMonkie** [comment]
@cooppor 
- 感谢您的肯定，很高兴能让使用者感到方便
- 两个建议都非常好，再次感谢~

**Comment by CoderMonkie** [comment]
@cooppor 

v2.0.2 里添加了两个配置项，默认值如下：

```js
{
  zIndex: 10000,
  debug: false,
}
```

**Comment by cooppor** [comment]
> @cooppor
> 
> v2.0.2 里添加了两个配置项，默认值如下：
> 
> ```js
> {
>   zIndex: 10000,
>   debug: false,
> }
> ```

已更新，很好用，非常感谢！
